#!/bin/sh

##
## Inputs
##

riverctl map normal Super+Shift Return spawn kitty
riverctl map normal Super Space spawn "tofi-drun | xargs -0 riverctl spawn"

# close current window
riverctl map normal Super Q close

# exit river
riverctl map normal Super+Shift E exit

# select next/previous window
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# move window up/down in stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# adjust main ratio
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-ratio +0.05"

# add/remove windows from main
riverctl map normal Super Comma send-layout-cmd rivertile "main-count +1"
riverctl map normal Super Period send-layout-cmd rivertile "main-count -1"

# move to top of stack
riverctl map normal Super Return zoom

# move with mouse
riverctl map-pointer normal Super BTN_LEFT move-view

# resize with mouse
riverctl map-pointer normal Super+Shift BTN_LEFT resize-view

##
## Behavior
##

# natural scroll direction
riverctl input *_Touchpad natural-scroll enabled
riverctl input *_Touchpad disable-while-typing enabled
riverctl input *_Touchpad tap enabled

riverctl default-layout rivertile
rivertile &
