#!/bin/sh

##
## Inputs
##

riverctl map normal Super+Shift Return spawn kitty
riverctl map normal Super Space spawn "tofi-drun | xargs -0 riverctl spawn"

# close current window
riverctl map normal Super Q close

# exit river
riverctl map normal Super+Shift E exit

# select next/previous window
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# move window up/down in stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# adjust main ratio
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-ratio +0.05"

# add/remove windows from main
riverctl map normal Super Comma send-layout-cmd rivertile "main-count +1"
riverctl map normal Super Period send-layout-cmd rivertile "main-count -1"

# move to top of stack
riverctl map normal Super Return zoom

# toggle full-screen for current window
riverctl map normal Super+Control+Alt F toggle-fullscreen

# toggle float for current window
riverctl map normal Super+Control+Alt T toggle-float

# move with mouse
riverctl map-pointer normal Super BTN_LEFT move-view

# resize with mouse
riverctl map-pointer normal Super+Shift BTN_LEFT resize-view

##
## Tags
##

for i in $(seq 1 9)
do
  tags=$((1 << ($i - 1)))

  # focus given tag
  riverctl map normal Super $i set-focused-tags $tags

  # move window to given tag
  riverctl map normal Super+Shift $i set-view-tags $tags
done

##
## Shortcuts
##
riverctl map normal Super 4 spawn 'grim'
riverctl map normal Super+Shift 4 spawn 'grim -g "$(slurp)"'

##
## Function Keys
##

for mode in normal locked
do
  riverctl map $mode None XF86AudioRaiseVolume spawn 'pamixer -i 5'
  riverctl map $mode None XF86AudioLowerVolume spawn 'pamixer -d 5'
  riverctl map $mode None XF86AudioMute spawn 'pamixer --toggle-mute'

  riverctl map $mode None XF86AudioPlay spawn 'playerctl play-pause'
  riverctl map $mode None XF86AudioPrev spawn 'playerctl previous'
  riverctl map $mode None XF86AudioNext spawn 'playerctl next'

  riverctl map $mode None XF86MonBrightnessUp spawn 'light -A 20'
  riverctl map $mode None XF86MonBrightnessDown spawn 'light -U 20'
done

##
## Behavior
##

# natural scroll direction
riverctl input *_Touchpad natural-scroll enabled
riverctl input *_Touchpad disable-while-typing enabled
riverctl input *_Touchpad tap enabled

riverctl default-layout rivertile

##
## Startup
##

[ -f /home/matt/background.png ] && swaybg -i /home/matt/background.png -m fill &
waybar &
rivertile &
