
k9s:
  refreshRate: 2 # in seconds
  logger:
    tail: 500
    buffer: 5000
    fullScreen: true
    textWrap: true
  ui:
    headless: true
    defaultsToFullScreen: true
    # ^ documented on website as `logger.fullScreen` but in code shows up as
    # `ui.defaultsToFullScreen`.

